### PR TITLE
Feature user objects

### PR DESCRIPTION
**Pull request by logangorence**
[Review on Reviewable](https://reviewable.io/reviews/directmyfile/irc.dart/23)

### CODE REVIEW

**Comment by kaendfinger** [comment]
<sup>**[lib/src/client/user.dart, line 22 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQ4bK9OsqnQ06iCKw)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/user.dart#L22)):</sup>
This line is unnecessary.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/directmyfile/irc.dart/23)

**Comment by logangorence** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/client/events.dart, line 523 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQHcqElWn582emwRH)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/events.dart#L523)):</sup>
Document

---

<sup>**[lib/src/client/events.dart, line 524 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQJChKLz_GVkrxa3d)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/events.dart#L524)):</sup>
Document

---

<sup>**[lib/src/client/events.dart, line 775 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQEwomcBK6BeeakjJ)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/events.dart#L775)):</sup>
Document

---

<sup>**[lib/src/client/server.dart, line 3 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQC4pdlvt4Qc6RFfH)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/server.dart#L3)):</sup>
Document

---

<sup>**[lib/src/client/server.dart, line 5 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQBADysOLGWXwkuXu)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/server.dart#L5)):</sup>
Document

---

<sup>**[lib/src/client/target.dart, line 1 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWPrk_gnxoSqSJsTOz)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/target.dart#L1)):</sup>
Rename file to entity.dart

---

<sup>**[lib/src/client/user.dart, line 13 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQ-uKWsKOgxZxdzVd)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/user.dart#L13)):</sup>
Document

---

<sup>**[lib/src/client/user.dart, line 15 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQ1Ax3aNdeTrBaqAC)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/user.dart#L15)):</sup>
Document

---

<sup>**[lib/src/client/user.dart, line 17 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQ279eJVQm-BSsV6P)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/user.dart#L17)):</sup>
Document

---

<sup>**[lib/src/client/user.dart, line 19 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWQ34gwjkfYQHmEadw)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/user.dart#L19)):</sup>
Document

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/directmyfile/irc.dart/23)

**Comment by kaendfinger** [comment]
<sup>**[lib/src/client/client.dart, line 894 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWRUHJIgYknL1s2Gj2)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/client/client.dart#L894)):</sup>
This branch is still needed. I don't believe the rest is though. Can you test this to ensure just in case?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/directmyfile/irc.dart/23)

**Comment by logangorence** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/parser/hostmask.dart, line 43 \[r1\]](https://reviewable.io:443/reviews/directmyfile/irc.dart/23#-JtWRlskIKDKh6KYBiXS)** ([raw file](https://github.com/directmyfile/irc.dart/blob/8181ebc3d1bb30e3b290ea2824e532b8182add3c/lib/src/parser/hostmask.dart#L43)):</sup>
Remove

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/directmyfile/irc.dart/23)

**Pull request merged**
